# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

factions = ["UCM", "Scourge", "PHR", "Shaltari"]

factions.each do |faction|
	Faction.create(name: faction)
end

battlegroup_types = {
									'Flag' 				=> 2,
									'Vanguard'		=> 3,
									'Line'				=> 3,
									'Pathfinder' 	=> 3
									}

battlegroup_types.each do |name, group_limit|
	BattlegroupType.create(name: name, group_limit: group_limit)
end

tonnages = ['L', 'M', 'H', 'S']

tonnages.each do |ton|
	Tonnage.create(tonnage: ton)
end

ucm_ships = [
{ name: 'Beijing',
scan: '8"',
signature: '12"',
thrust: '6"',
hull: '18',
armor: '3+',
point_defense: '10',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 4,
faction_id: 1,
cost:155 },
{ name: 'New York',
scan: '8"',
signature: '12"',
thrust: '6"',
hull: '18',
armor: '3+',
point_defense: '10',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 4,
faction_id: 1,
cost: 260 },
{ name: 'Tokyo',
scan: '8"',
signature: '12"',
thrust: '6"',
hull: '18',
armor: '3+',
point_defense: '10',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 4,
faction_id: 1,
cost: 220 },
{ name: 'Atlantis',
scan: '6"',
signature: '6"',
thrust: '8"',
hull: '14',
armor: '3+',
point_defense: '7',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 3,
faction_id: 1,
cost: 205 },
{ name: 'Avalon',
scan: '6"',
signature: '6"',
thrust: '8"',
hull: '14',
armor: '3+',
point_defense: '7',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 3,
faction_id: 1,
cost: 195 },
{ name: 'Moscow',
scan: '6"',
signature: '6"',
thrust: '7"',
hull: '12',
armor: '3+',
point_defense: '5',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 3,
faction_id: 1,
cost: 163 },
{ name: 'St. Petersburg',
scan: '6"',
signature: '6"',
thrust: '7"',
hull: '12',
armor: '3+',
point_defense: '5',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 3,
faction_id: 1,
cost: 155 },
{ name: 'Rio',
scan: '6"',
signature: '6"',
thrust: '8"',
hull: '10',
armor: '3+',
point_defense: '5',
min_group_size: 1,
max_group_size: 2,
tonnage_id: 2,
faction_id: 1,
cost: 105 },
{ name: 'Berlin',
scan: '6"',
signature: '6"',
thrust: '8"',
hull: '10',
armor: '3+',
point_defense: '5',
min_group_size: 1,
max_group_size: 2,
tonnage_id: 2,
faction_id: 1,
cost: 105 },
{ name: 'Madrid',
scan: '6"',
signature: '6"',
thrust: '8"',
hull: '10',
armor: '3+',
point_defense: '5',
min_group_size: 1,
max_group_size: 2,
tonnage_id: 2,
faction_id: 1,
cost: 79 },
{ name: 'Seattle',
scan: '6"',
signature: '6"',
thrust: '8"',
hull: '10',
armor: '3+',
point_defense: '5',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 2,
faction_id: 1,
cost: 132 },
{ name: 'Osaka',
scan: '6"',
signature: '6"',
thrust: '10"',
hull: '8',
armor: '4+',
point_defense: '5',
min_group_size: 2,
max_group_size: 3,
tonnage_id: 2,
faction_id: 1,
cost: 86 },
{ name: 'New Cairo',
scan: '6"',
signature: '6"',
thrust: '10"',
hull: '8',
armor: '4+',
point_defense: '5',
min_group_size: 2,
max_group_size: 3,
tonnage_id: 2,
faction_id: 1,
cost: 88 },
{ name: 'San Francisco',
scan: '6"',
signature: '6"',
thrust: '8"',
hull: '10',
armor: '3+',
point_defense: '5',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 2,
faction_id: 1,
cost: 111 },
{ name: 'Toulon',
scan: '6"',
signature: '3"',
thrust: '10"',
hull: '4',
armor: '4+',
point_defense: '3',
min_group_size: 2,
max_group_size: 4,
tonnage_id: 1,
faction_id: 1,
cost: 35 },
{ name: 'Taipei',
scan: '6"',
signature: '3"',
thrust: '10"',
hull: '4',
armor: '4+',
point_defense: '3',
min_group_size: 2,
max_group_size: 6,
tonnage_id: 1,
faction_id: 1,
cost: 39 },
{ name: 'Jakarta',
scan: '6"',
signature: '3"',
thrust: '10"',
hull: '4',
armor: '4+',
point_defense: '3',
min_group_size: 1,
max_group_size: 4,
tonnage_id: 1,
faction_id: 1,
cost: 32 },
{ name: 'Lima',
scan: '6"',
signature: '3"',
thrust: '10"',
hull: '4',
armor: '4+',
point_defense: '3',
min_group_size: 1,
max_group_size: 2,
tonnage_id: 1,
faction_id: 1,
cost: 37 },
{ name: 'New Orleans',
scan: '6"',
signature: '3"',
thrust: '10"',
hull: '4',
armor: '4+',
point_defense: '3',
min_group_size: 1,
max_group_size: 2,
tonnage_id: 1,
faction_id: 1,
cost: 32 },
{ name: 'Santiago',
scan: '6"',
signature: '2"',
thrust: '14"',
hull: '2',
armor: '5+',
point_defense: '2',
min_group_size: 1,
max_group_size: 3,
tonnage_id: 1,
faction_id: 1,
cost: 22 }
] 

ucm_ships.each do |ship|
	Ship.create(ship)
end

scourge_ships = [
{ name: 'Daemon',
scan: '8"',
signature: '14"',
thrust: '8"',
hull: '18',
armor: '3+',
point_defense: '12',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 4,
faction_id: 2,
cost: 260 },
{ name: 'Dragon',
scan: '8"',
signature: '14"',
thrust: '8"',
hull: '18',
armor: '3+',
point_defense: '12',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 4,
faction_id: 2,
cost: 265 },
{ name: 'Basilisk',
scan: '6"',
signature: '8"',
thrust: '10"',
hull: '14',
armor: '4+',
point_defense: '8',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 3,
faction_id: 2,
cost: 205 },
{ name: 'Manticore',
scan: '6"',
signature: '8"',
thrust: '10"',
hull: '14',
armor: '4+',
point_defense: '8',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 3,
faction_id: 2,
cost: 190 },
{ name: 'Shenlong',
scan: '6"',
signature: '8"',
thrust: '8"',
hull: '12',
armor: '4+',
point_defense: '6',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 3,
faction_id: 2,
cost: 170 },
{ name: 'Raiju',
scan: '6"',
signature: '8"',
thrust: '8"',
hull: '12',
armor: '4+',
point_defense: '6',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 3,
faction_id: 2,
cost: 160},
{ name:'Sphinx',
scan: '6"',
signature: '8"',
thrust: '10"',
hull: '10',
armor: '4+',
point_defense: '6',
min_group_size: 1,
max_group_size: 2,
tonnage_id: 2,
faction_id: 2,
cost: 115 },
{ name: 'Wyvern',
scan: '6"',
signature: '8"',
thrust: '10"',
hull: '10',
armor: '4+',
point_defense: '6',
min_group_size: 1,
max_group_size: 2,
tonnage_id: 2,
faction_id: 2,
cost: 105 },
{ name: 'Ifrit',
scan: '6"',
signature: '8"',
thrust: '10"',
hull: '10',
armor: '4+',
point_defense: '6',
min_group_size: 1,
max_group_size: 2,
tonnage_id: 2,
faction_id: 2,
cost: 110 },
{ name: 'Hydra',
scan: '6"',
signature: '8"',
thrust: '10"',
hull: '10',
armor: '4+',
point_defense: '6',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 2,
faction_id: 2,
cost: 140 },
{ name: 'Chimera',
scan: '6"',
signature: '8"',
thrust: '10"',
hull: '10',
armor: '4+',
point_defense: '6',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 2,
faction_id: 2,
cost: 105 },
{ name: 'Strix',
scan: '6"',
signature: '8"',
thrust: '12"',
hull: '8',
armor: '5+',
point_defense: '2',
min_group_size: 2,
max_group_size: 3,
tonnage_id: 2,
faction_id: 2,
cost: 90 },
{ name: 'Yokai',
scan: '6"',
signature: '8"',
thrust: '12"',
hull: '8',
armor: '5+',
point_defense: '2',
min_group_size: 2,
max_group_size: 3,
tonnage_id: 2,
faction_id: 2,
cost: 95},
{ name: 'Harpy',
scan: '6"',
signature: '3"',
thrust: '12"',
hull: '4',
armor: '5+',
point_defense: '4',
min_group_size: 2,
max_group_size: 4,
tonnage_id: 1,
faction_id: 2,
cost: 42},
{ name: 'Djinn',
scan: '6"',
signature: '3"',
thrust: '12"',
hull: '4',
armor: '5+',
point_defense: '4',
min_group_size: 2,
max_group_size: 6,
tonnage_id: 1,
faction_id: 2,
cost: 43},
{ name: 'Charybdis',
scan: '6"',
signature: '3"',
thrust: '12"',
hull: '4',
armor: '5+',
point_defense: '4',
min_group_size: 2,
max_group_size: 4,
tonnage_id: 1,
faction_id: 2,
cost: 35},
{ name: 'Scylla',
scan: '6"',
signature: '3"',
thrust: '12"',
hull: '4',
armor: '5+',
point_defense: '4',
min_group_size: 2,
max_group_size: 4,
tonnage_id: 1,
faction_id: 2,
cost: 42 },
{ name: 'Gargoyle',
scan: '6"',
signature: '3"',
thrust: '12"',
hull: '4',
armor: '5+',
point_defense: '4',
min_group_size: 1,
max_group_size: 2,
tonnage_id: 1,
faction_id: 2,
cost: 32 },
{ name: 'Nickar',
scan: '6"',
signature: '2"',
thrust: '16"',
hull: '2',
armor: '6+',
point_defense: '2',
min_group_size: 1,
max_group_size: 3,
tonnage_id: 1,
faction_id: 2,
cost: 22 }
]

scourge_ships.each do |ship|
	Ship.create(ship)
end

phr_ships = [
{ name: 'Heracles',
scan: '10"',
signature: '12"',
thrust: '6"',
hull: '22',
armor: '3+',
point_defense: '10',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 4,
faction_id: 3,
cost: 285 },
{ name: 'Minos',
scan: '10"',
signature: '12"',
thrust: '6"',
hull: '22',
armor: '3+',
point_defense: '10',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 4,
faction_id: 3,
cost: 285 },
{ name: 'Leonidas',
scan: '8"',
signature: '6"',
thrust: '10"',
hull: '15',
armor: '3+',
point_defense: '7',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 3,
faction_id: 3,
cost: 195 },
{ name: 'Scipio',
scan: '8"',
signature: '6"',
thrust: '10"',
hull: '15',
armor: '3+',
point_defense: '7',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 3,
faction_id: 3,
cost: 210 },
{ name: 'Hector',
scan: '8"',
signature: '6"',
thrust: '7"',
hull: '13',
armor: '3+',
point_defense: '5',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 3,
faction_id: 3,
cost: 170 },
{ name: 'Achilles',
scan: '8"',
signature: '6"',
thrust: '7"',
hull: '13',
armor: '3+',
point_defense: '5',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 3,
faction_id: 3,
cost: 165 },
{ name: 'Bellerophon',
scan: '8"',
signature: '6"',
thrust: '7"',
hull: '13',
armor: '3+',
point_defense: '5',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 3,
faction_id: 3,
cost: 180 },
{ name: 'Orpheus',
scan: '8"',
signature: '6"',
thrust: '7"',
hull: '13',
armor: '3+',
point_defense: '5',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 2,
faction_id: 3,
cost: 130 },
{ name: 'Ganymede',
scan: '8"',
signature: '6"',
thrust: '7"',
hull: '13',
armor: '3+',
point_defense: '5',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 2,
faction_id: 3,
cost: 135 },
{ name: 'Orion',
scan: '8"',
signature: '6"',
thrust: '8"',
hull: '11',
armor: '3+',
point_defense: '5',
min_group_size: 1,
max_group_size: 2,
tonnage_id: 2,
faction_id: 3,
cost: 107 },
{ name: 'Ajax',
scan: '8"',
signature: '6"',
thrust: '8"',
hull: '11',
armor: '3+',
point_defense: '5',
min_group_size: 1,
max_group_size: 2,
tonnage_id: 2,
faction_id: 3,
cost: 100 },
{ name: 'Perseus',
scan: '8"',
signature: '6"',
thrust: '8"',
hull: '11',
armor: '3+',
point_defense: '5',
min_group_size: 1,
max_group_size: 1,
tonnage_id: 2,
faction_id: 3,
cost: 105 },
{ name: 'Ikarus',
scan: '8"',
signature: '6"',
thrust: '8"',
hull: '11',
armor: '3+',
point_defense: '5',
min_group_size: 1,
max_group_size: 2,
tonnage_id: 2,
faction_id: 3,
cost: 115 },
{ name: 'Theseus',
scan: '8"',
signature: '6"',
thrust: '10"',
hull: '9',
armor: '3+',
point_defense: '2',
min_group_size: 1,
max_group_size: 3,
tonnage_id: 2,
faction_id: 3,
cost: 89 },
{ name: 'Europa',
scan: '8"',
signature: '3"',
thrust: '10"',
hull: '5',
armor: '3+',
point_defense: '3',
min_group_size: 2,
max_group_size: 4,
tonnage_id: 1,
faction_id: 3,
cost: 40 },
{ name: 'Pandora',
scan: '8"',
signature: '3"',
thrust: '10"',
hull: '5',
armor: '3+',
point_defense: '3',
min_group_size: 2,
max_group_size: 4,
tonnage_id: 1,
faction_id: 3,
cost: 50 },
{ name: 'Calypso',
scan: '8"',
signature: '3"',
thrust: '10"',
hull: '5',
armor: '3+',
point_defense: '3',
min_group_size: 1,
max_group_size: 2,
tonnage_id: 1,
faction_id: 3,
cost: 37 },
{ name: 'Andromeda',
scan: '8"',
signature: '3"',
thrust: '10"',
hull: '5',
armor: '3+',
point_defense: '3',
min_group_size: 2,
max_group_size: 4,
tonnage_id: 1,
faction_id: 3,
cost: 42 },
{ name: 'Medea',
scan: '8"',
signature: '3"',
thrust: '10"',
hull: '5',
armor: '3+',
point_defense: '3',
min_group_size: 1,
max_group_size: 2,
tonnage_id: 1,
faction_id: 3,
cost: 39 },
{ name: 'Echo',
scan: '8"',
signature: '2"',
thrust: '12"',
hull: '2',
armor: '4+',
point_defense: '2',
min_group_size: 1,
max_group_size: 3,
tonnage_id: 1,
faction_id: 3,
cost: 30 }
]

phr_ships.each do |ship|
	Ship.create(ship)
end

shaltari_ships = [
{ name: 'Diamond',
scan: '12"',
signature: '4"/20"',
thrust: '8"',
hull: '18',
armor: '4+/4+',
point_defense: '12',
min_group_size: 1,
max_group_size: 1, 
tonnage_id: 4,
faction_id: 4,
cost: 270 },
{ name: 'Platinum',
scan: '12"',
signature: '4"/20"',
thrust: '8"',
hull: '18',
armor: '4+/4+',
point_defense: '12',
min_group_size: 1,
max_group_size: 1, 
tonnage_id: 4,
faction_id: 4,
cost: 270 },
{ name: 'Adamant',
scan: '12"',
signature: '3"/16"',
thrust: '10"',
hull: '13',
armor: '5+/4+',
point_defense: '9',
min_group_size: 1,
max_group_size: 1, 
tonnage_id: 3,
faction_id: 4,
cost: 200 },
{ name: 'Palladium',
scan: '12"',
signature: '3"/16"',
thrust: '10"',
hull: '13',
armor: '5+/4+',
point_defense: '9',
min_group_size: 1,
max_group_size: 1, 
tonnage_id: 3,
faction_id: 4,
cost: 185 },
{ name: 'Onyx',
scan: '12"',
signature: '3"/16"',
thrust: '8"',
hull: '11',
armor: '5+/4+',
point_defense: '9',
min_group_size: 1,
max_group_size: 1, 
tonnage_id: 3,
faction_id: 4,
cost: 165 },
{ name: 'Obsidian',
scan: '12"',
signature: '3"/16"',
thrust: '8"',
hull: '11',
armor: '5+/4+',
point_defense: '9',
min_group_size: 1,
max_group_size: 1, 
tonnage_id: 3,
faction_id: 4,
cost: 155 },
{ name: 'Jet',
scan: '12"',
signature: '3"/16"',
thrust: '8"',
hull: '11',
armor: '5+/4+',
point_defense: '9',
min_group_size: 1,
max_group_size: 1, 
tonnage_id: 3,
faction_id: 4,
cost: 165 },
{ name: 'Amber',
scan: '12"',
signature: '3"/16"',
thrust: '10"',
hull: '9',
armor: '5+/4+',
point_defense: '9',
min_group_size: 1,
max_group_size: 2, 
tonnage_id: 2,
faction_id: 4,
cost: 110 },
{ name: 'Granite',
scan: '12"',
signature: '3"/16"',
thrust: '10"',
hull: '9',
armor: '5+/4+',
point_defense: '9',
min_group_size: 1,
max_group_size: 2, 
tonnage_id: 2,
faction_id: 4,
cost: 100 },
{ name: 'Turquoise',
scan: '12"',
signature: '3"/16"',
thrust: '10"',
hull: '9',
armor: '5+/4+',
point_defense: '9',
min_group_size: 1,
max_group_size: 2, 
tonnage_id: 2,
faction_id: 4,
cost: 115 },
{ name: 'Basalt',
scan: '12"',
signature: '3"/16"',
thrust: '10"',
hull: '9',
armor: '5+/4+',
point_defense: '9',
min_group_size: 1,
max_group_size: 1, 
tonnage_id: 2,
faction_id: 4,
cost: 145 },
{ name: 'Emerald',
scan: '12"',
signature: '3"/16"',
thrust: '10"',
hull: '9',
armor: '5+/4+',
point_defense: '9',
min_group_size: 1,
max_group_size: 1, 
tonnage_id: 2,
faction_id: 4,
cost: 100 },
{ name: 'Azurite',
scan: '12"',
signature: '3"/16"',
thrust: '12"',
hull: '7',
armor: '5+/4+',
point_defense: '6',
min_group_size: 2,
max_group_size: 3, 
tonnage_id: 2,
faction_id: 4,
cost: 85 },
{ name: 'Aquamarine',
scan: '12"',
signature: '3"/16"',
thrust: '12"',
hull: '7',
armor: '5+/4+',
point_defense: '6',
min_group_size: 2,
max_group_size: 3, 
tonnage_id: 2,
faction_id: 4,
cost: 85 },
{ name: 'Topaz',
scan: '12"',
signature: '2"/12"',
thrust: '12"',
hull: '4',
armor: '5+/4+',
point_defense: '6',
min_group_size: 2,
max_group_size: 4, 
tonnage_id: 1,
faction_id: 4,
cost: 45 },
{ name: 'Jade',
scan: '12"',
signature: '2"/12"',
thrust: '12"',
hull: '4',
armor: '5+/4+',
point_defense: '6',
min_group_size: 2,
max_group_size: 4, 
tonnage_id: 1,
faction_id: 4,
cost: 45 },
{ name: 'Opal',
scan: '12"',
signature: '2"/12"',
thrust: '12"',
hull: '4',
armor: '5+/4+',
point_defense: '6',
min_group_size: 1,
max_group_size: 2, 
tonnage_id: 1,
faction_id: 4,
cost: 40 },
{ name: 'Amethyst',
scan: '12"',
signature: '2"/12"',
thrust: '12"',
hull: '4',
armor: '5+/4+',
point_defense: '6',
min_group_size: 1,
max_group_size: 2, 
tonnage_id: 1,
faction_id: 4,
cost: 48 },
{ name: 'Voidgate',
scan: '12"',
signature: '1"/8"',
thrust: '12"',
hull: '3',
armor: '5+/5+',
point_defense: '6',
min_group_size: 1,
max_group_size: 3, 
tonnage_id: 1,
faction_id: 4,
cost: 15 },
{ name: 'Glass',
scan: '8"',
signature: '1"/8"',
thrust: '16"',
hull: '1',
armor: '5+/5+',
point_defense: '3',
min_group_size: 2,
max_group_size: 6, 
tonnage_id: 1,
faction_id: 4,
cost: 36 }
]

shaltari_ships.each do |ship|
	Ship.create(ship)
end